# Generated by Django 2.1.5 on 2022-02-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='urls',
            new_name='url',
        ),
    ]
